# GentlyOS installed system configuration
# This is used after installation to the target system
{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
  ];

  system.stateVersion = "24.11";

  # Boot loader
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
    timeout = 5;
  };

  # Networking
  networking = {
    hostName = "gently";
    networkmanager.enable = true;
  };

  # Time zone
  time.timeZone = "UTC";

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";

  # Users
  users.users.gently = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    initialPassword = "gently";  # Change after first login!
  };

  # Allow wheel group to sudo
  security.sudo.wheelNeedsPassword = true;

  # System packages
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    curl
    htop
  ];

  # Enable SSH
  services.openssh.enable = true;

  # Nix settings
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  # Garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
}
