#!/bin/bash
# GentlyOS Master Installer
# The Demon Who Builds

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
RUST_DIR="$ROOT_DIR/GentlyOS-Rusted-Metal"
SPEC_FILE="$SCRIPT_DIR/../specs/machine.json"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${GREEN}[INSTALL]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
header() { echo -e "\n${CYAN}=== $1 ===${NC}\n"; }

echo "========================================"
echo "      GentlyOS Master Installer"
echo "  The Demon Builds Your Kingdom"
echo "========================================"
echo ""

# Step 1: Validate environment
header "Step 1: Validating Environment"
if ! "$SCRIPT_DIR/validate.sh"; then
    error "Environment validation failed"
    exit 1
fi

# Step 2: Detect specs
header "Step 2: Detecting Hardware Specs"
"$SCRIPT_DIR/detect-specs.sh" "$SPEC_FILE"

# Step 3: Read recommendations
header "Step 3: Reading Recommendations"
if [[ -f "$SPEC_FILE" ]]; then
    if command -v jq &> /dev/null; then
        FEATURES=$(jq -r '.recommendations.features | join(",")' "$SPEC_FILE")
        THREADS=$(jq -r '.recommendations.thread_count' "$SPEC_FILE")
    else
        FEATURES="fastembed"
        THREADS=2
    fi
    log "Features: $FEATURES"
    log "Threads: $THREADS"
else
    warn "No spec file found, using defaults"
    FEATURES="fastembed"
    THREADS=2
fi

# Step 4: Build
header "Step 4: Building GentlyOS"
cd "$RUST_DIR"

log "Building foundation crates..."
cargo build -p gently-core -p gently-codie -p gently-artisan -j$THREADS 2>&1 | tail -5

log "Building tier 1 crates..."
cargo build -p gently-btc -p gently-dance -p gently-cipher -j$THREADS 2>&1 | tail -5

log "Building tier 2 crates..."
cargo build -p gently-feed -p gently-security -j$THREADS 2>&1 | tail -5

log "Building tier 3 crates..."
cargo build -p gently-alexandria -p gently-search -j$THREADS 2>&1 | tail -5

log "Building tier 4 crates..."
cargo build -p gently-agents --features codie -j$THREADS 2>&1 | tail -5
cargo build -p gently-brain -j$THREADS 2>&1 | tail -5

log "Building applications..."
cargo build -p gently-cli -j$THREADS 2>&1 | tail -5

# Step 5: Run tests
header "Step 5: Running Tests"
log "Running core tests..."
cargo test -p gently-core -p gently-codie --no-fail-fast 2>&1 | tail -10

# Step 6: Create symlinks
header "Step 6: Creating Symlinks"
if [[ -d "$HOME/.local/bin" ]]; then
    ln -sf "$RUST_DIR/target/debug/gently" "$HOME/.local/bin/gently" 2>/dev/null || true
    log "Symlink created: ~/.local/bin/gently"
else
    warn "~/.local/bin not found, skipping symlink"
fi

# Step 7: Initialize
header "Step 7: Initializing GentlyOS"
mkdir -p "$HOME/.gently"
if [[ ! -f "$HOME/.gently/config.toml" ]]; then
    cat > "$HOME/.gently/config.toml" << EOF
# GentlyOS Configuration
# Generated by installer

[general]
version = "1.0.0"

[features]
$( [[ "$FEATURES" == *"cuda"* ]] && echo "cuda = true" || echo "cuda = false" )
$( [[ "$FEATURES" == *"fastembed"* ]] && echo "fastembed = true" || echo "fastembed = false" )

[performance]
threads = $THREADS
EOF
    log "Config created: ~/.gently/config.toml"
fi

# Done
header "Installation Complete"
echo ""
echo "GentlyOS has been installed successfully."
echo ""
echo "Quick start:"
echo "  gently --help        Show available commands"
echo "  gently status        Show system status"
echo "  gently setup         Run setup wizard"
echo ""
echo "The Demon has built your kingdom. May it stand eternal."
